zoomcamp_dbt:
  outputs:
    dev:
      dataset: zoomcamp_test
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /tmp/<service_account>.json
      location: US
      method: service-account
      priority: interactive
      project: golden-union-392713
      threads: 1
      type: bigquery
  target: dev
