zoomcamp_dbt:
  outputs:
    dev:
      dataset: <Your Dataset Name>
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /tmp/service_account.json
      location: US
      method: service-account
      priority: interactive
      project: <Your GCP Project>
      threads: 1
      type: bigquery
  target: dev
